import { createFileRoute } from "@tanstack/react-router";
import heroImage from "../assets/kraft-hero.jpg";
import { Eyebrow, PageFrame, PageIntro, Reveal } from "../components/KraftSite";

export const Route = createFileRoute("/about")({
  head: () => ({ meta: [
    { title: "About — Kraft Studios" }, { name: "description", content: "Kraft Studios is a hybrid design and engineering agency building culturally resonant, operationally sound digital ecosystems." },
    { property: "og:title", content: "About — Kraft Studios" }, { property: "og:description", content: "Building the engine. Designing the soul." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: AboutPage,
});
function AboutPage() { return <PageFrame><main><PageIntro number="03" label="About" title="Building the engine. Designing the soul" copy="Kraft Studios is a premium hybrid agency for organisations that refuse to choose between expressive design and robust technology." /><section className="border-t border-ink/10"><div className="site-shell grid grid-cols-12 gap-6 py-20 lg:py-28"><Reveal className="col-span-12 lg:col-span-5"><img src={heroImage} alt="A designer aligning marks by hand" loading="lazy" width={1024} height={1280} className="aspect-[4/5] w-full object-cover" /></Reveal><div className="col-span-12 lg:col-span-6 lg:col-start-7"><Reveal><Eyebrow>Our point of view</Eyebrow><p className="mt-6 font-display text-3xl font-medium leading-tight lg:text-5xl">A brand is not a surface placed over a system. It is the system people can feel.</p></Reveal><Reveal delay={100}><div className="mt-12 grid gap-8 border-t border-ink/15 pt-8 sm:grid-cols-2"><div><h2 className="font-display text-xl font-semibold">Culturally resonant</h2><p className="mt-3 text-sm leading-relaxed text-ink/60">We draw from living visual traditions without reducing them to decoration.</p></div><div><h2 className="font-display text-xl font-semibold">Operationally exact</h2><p className="mt-3 text-sm leading-relaxed text-ink/60">Every interface is backed by architecture that remains useful under real pressure.</p></div></div></Reveal></div></div></section><section className="border-t border-ink/10"><div className="site-shell py-20"><Eyebrow>The ecosystem</Eyebrow><div className="mt-10 grid gap-px bg-ink/10 md:grid-cols-3"><Reveal className="service-panel"><h2 className="font-display text-2xl font-semibold">Kraft Studios</h2><p className="mt-4 text-sm leading-relaxed text-ink/60">The hub for high-value creative engineering, visual branding and custom software.</p></Reveal><Reveal className="service-panel" delay={80}><h2 className="font-display text-2xl font-semibold">Brush.in</h2><p className="mt-4 text-sm leading-relaxed text-ink/60">The product and fulfilment spoke connecting creative assets with physical deployment.</p></Reveal><Reveal className="service-panel" delay={160}><h2 className="font-display text-2xl font-semibold">The Notice Board</h2><p className="mt-4 text-sm leading-relaxed text-ink/60">The innovation sandbox proving autonomous data architecture at real-world scale.</p></Reveal></div></div></section></main></PageFrame> }
